"""Immutable project-scoped PRICE_EVIDENCE authority, Issue 131."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "d7e8f9a0b1c2"
down_revision = "c6d7e8f9a0b1"
branch_labels = None
depends_on = None
TABLES = ('price_evidence_receipts', 'project_price_evidence_sources', 'project_price_evidence_decisions', 'project_price_evidence_confirmations', 'project_price_evidence_withdrawals')


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_evidence_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('contract_version', sa.String(length=64), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('response_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], name='fk_pe_receipt_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_pe_receipt_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'actor_user_id', 'session_id'], ['workbench_sessions.project_id', 'workbench_sessions.user_id', 'workbench_sessions.id'], name='fk_pe_receipt_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', name='uq_pe_command'),
    sa.UniqueConstraint('organization_id', 'project_id', 'actor_user_id', 'session_id', 'id', name='uq_pe_receipt_scope')
    )
    op.create_table('project_price_evidence_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('seal_id', sa.Uuid(), nullable=False),
    sa.Column('pre_row_version', sa.Integer(), nullable=False),
    sa.Column('post_row_version', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('invocation_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('internet_survey', 'unit_price_explanation', 'prior_appraisal_result')", name='chk_pe_source_category'),
    sa.CheckConstraint('pre_row_version > 0 AND post_row_version = pre_row_version + 1', name='chk_pe_source_version'),
    sa.CheckConstraint('revision > 0 AND ((revision = 1 AND predecessor_id IS NULL) OR (revision > 1 AND predecessor_id IS NOT NULL AND predecessor_id != id))', name='chk_pe_source_prior'),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_events.id'], name='fk_pe_source_audit', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], name='fk_pe_source_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'actor_user_id', 'session_id', 'receipt_id'], ['price_evidence_receipts.organization_id', 'price_evidence_receipts.project_id', 'price_evidence_receipts.actor_user_id', 'price_evidence_receipts.session_id', 'price_evidence_receipts.id'], name='fk_pe_source_receipt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'predecessor_id'], ['project_price_evidence_sources.organization_id', 'project_price_evidence_sources.project_id', 'project_price_evidence_sources.id'], name='fk_pe_source_prior', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'seal_id'], ['project_asset_review_seals.organization_id', 'project_asset_review_seals.project_id', 'project_asset_review_seals.id'], name='fk_pe_source_seal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_pe_source_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'actor_user_id', 'session_id'], ['workbench_sessions.project_id', 'workbench_sessions.user_id', 'workbench_sessions.id'], name='fk_pe_source_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', name='uq_pe_source_audit'),
    sa.UniqueConstraint('organization_id', 'project_id', 'id', name='uq_pe_source_scope'),
    sa.UniqueConstraint('organization_id', 'project_id', 'source_id', 'revision', name='uq_pe_source_revision'),
    sa.UniqueConstraint('predecessor_id', name='uq_pe_source_successor'),
    sa.UniqueConstraint('receipt_id', name='uq_pe_source_receipt')
    )
    op.create_table('project_price_evidence_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_revision_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('predecessor_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('disposition', sa.String(length=32), nullable=False),
    sa.Column('review_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('seal_id', sa.Uuid(), nullable=False),
    sa.Column('pre_row_version', sa.Integer(), nullable=False),
    sa.Column('post_row_version', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('invocation_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(outcome = 'accepted' AND disposition = 'qualifying_basis') OR (outcome = 'rejected' AND disposition IN ('excluded_alternative', 'unresolved_concern'))", name='chk_pe_decision_outcome'),
    sa.CheckConstraint('pre_row_version > 0 AND post_row_version = pre_row_version + 1', name='chk_pe_decision_version'),
    sa.CheckConstraint('review_due_at > created_at', name='chk_pe_decision_deadline'),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_events.id'], name='fk_pe_decision_audit', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], name='fk_pe_decision_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'actor_user_id', 'session_id', 'receipt_id'], ['price_evidence_receipts.organization_id', 'price_evidence_receipts.project_id', 'price_evidence_receipts.actor_user_id', 'price_evidence_receipts.session_id', 'price_evidence_receipts.id'], name='fk_pe_decision_receipt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'evidence_revision_id'], ['project_price_evidence_sources.organization_id', 'project_price_evidence_sources.project_id', 'project_price_evidence_sources.id'], name='fk_pe_decision_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'predecessor_id'], ['project_price_evidence_decisions.organization_id', 'project_price_evidence_decisions.project_id', 'project_price_evidence_decisions.id'], name='fk_pe_decision_prior', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'seal_id'], ['project_asset_review_seals.organization_id', 'project_asset_review_seals.project_id', 'project_asset_review_seals.id'], name='fk_pe_decision_seal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_pe_decision_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'actor_user_id', 'session_id'], ['workbench_sessions.project_id', 'workbench_sessions.user_id', 'workbench_sessions.id'], name='fk_pe_decision_session', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'line_id'], ['project_asset_lines.project_id', 'project_asset_lines.id'], name='fk_pe_decision_line', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', name='uq_pe_decision_audit'),
    sa.UniqueConstraint('organization_id', 'project_id', 'id', name='uq_pe_decision_scope'),
    sa.UniqueConstraint('organization_id', 'project_id', 'line_id', 'source_id', 'post_row_version', name='uq_pe_decision_order'),
    sa.UniqueConstraint('predecessor_id', name='uq_pe_decision_successor'),
    sa.UniqueConstraint('receipt_id', name='uq_pe_decision_receipt'),
    sa.UniqueConstraint('relationship_id')
    )
    op.create_table('project_price_evidence_confirmations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('predecessor_id', sa.Uuid(), nullable=True),
    sa.Column('workbench_confirmation_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('seal_id', sa.Uuid(), nullable=False),
    sa.Column('pre_row_version', sa.Integer(), nullable=False),
    sa.Column('post_row_version', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('invocation_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pre_row_version > 0 AND post_row_version = pre_row_version + 1', name='chk_pe_confirmation_version'),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_events.id'], name='fk_pe_confirmation_audit', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], name='fk_pe_confirmation_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'actor_user_id', 'session_id', 'receipt_id'], ['price_evidence_receipts.organization_id', 'price_evidence_receipts.project_id', 'price_evidence_receipts.actor_user_id', 'price_evidence_receipts.session_id', 'price_evidence_receipts.id'], name='fk_pe_confirmation_receipt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'predecessor_id'], ['project_price_evidence_confirmations.organization_id', 'project_price_evidence_confirmations.project_id', 'project_price_evidence_confirmations.id'], name='fk_pe_confirmation_prior', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'seal_id'], ['project_asset_review_seals.organization_id', 'project_asset_review_seals.project_id', 'project_asset_review_seals.id'], name='fk_pe_confirmation_seal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'workbench_confirmation_id'], ['project_asset_workbench_confirmations.organization_id', 'project_asset_workbench_confirmations.project_id', 'project_asset_workbench_confirmations.id'], name='fk_pe_confirmation_upstream', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_pe_confirmation_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'actor_user_id', 'session_id'], ['workbench_sessions.project_id', 'workbench_sessions.user_id', 'workbench_sessions.id'], name='fk_pe_confirmation_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', name='uq_pe_confirmation_audit'),
    sa.UniqueConstraint('organization_id', 'project_id', 'id', name='uq_pe_confirmation_scope'),
    sa.UniqueConstraint('predecessor_id', name='uq_pe_confirmation_successor'),
    sa.UniqueConstraint('receipt_id', name='uq_pe_confirmation_receipt')
    )
    op.create_table('project_price_evidence_withdrawals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.String(length=24), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('seal_id', sa.Uuid(), nullable=False),
    sa.Column('pre_row_version', sa.Integer(), nullable=False),
    sa.Column('post_row_version', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('invocation_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_kind IN ('source', 'relationship', 'decision', 'confirmation')", name='chk_pe_withdrawal_target'),
    sa.CheckConstraint('pre_row_version > 0 AND post_row_version = pre_row_version + 1', name='chk_pe_withdrawal_version'),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_events.id'], name='fk_pe_withdrawal_audit', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], name='fk_pe_withdrawal_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'actor_user_id', 'session_id', 'receipt_id'], ['price_evidence_receipts.organization_id', 'price_evidence_receipts.project_id', 'price_evidence_receipts.actor_user_id', 'price_evidence_receipts.session_id', 'price_evidence_receipts.id'], name='fk_pe_withdrawal_receipt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'seal_id'], ['project_asset_review_seals.organization_id', 'project_asset_review_seals.project_id', 'project_asset_review_seals.id'], name='fk_pe_withdrawal_seal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_pe_withdrawal_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'actor_user_id', 'session_id'], ['workbench_sessions.project_id', 'workbench_sessions.user_id', 'workbench_sessions.id'], name='fk_pe_withdrawal_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', name='uq_pe_withdrawal_audit'),
    sa.UniqueConstraint('organization_id', 'project_id', 'id', name='uq_pe_withdrawal_scope'),
    sa.UniqueConstraint('receipt_id', name='uq_pe_withdrawal_receipt'),
    sa.UniqueConstraint('target_kind', 'target_id', name='uq_pe_withdrawal_target')
    )
    # ### end Alembic commands ###
    if op.get_context().dialect.name == "postgresql":
        op.execute("CREATE FUNCTION price_evidence_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ "
                   "BEGIN RAISE EXCEPTION 'PRICE_EVIDENCE facts are append-only'; END; $$")
        for table in TABLES:
            op.execute(f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
                       "FOR EACH ROW EXECUTE FUNCTION price_evidence_append_only()")


def downgrade():
    for table in reversed(TABLES):
        op.drop_table(table)
    if op.get_context().dialect.name == "postgresql":
        op.execute("DROP FUNCTION price_evidence_append_only()")
