"""Dedicated immutable supplier quotation authority, Issue 137."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision = "e8f9a0b1c2d3"
down_revision = "d7e8f9a0b1c2"
branch_labels = None
depends_on = None
TABLES = ('supplier_quote_receipts', 'supplier_quote_facts', 'supplier_quote_items')


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_quote_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('contract_version', sa.String(length=64), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('response_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], name='fk_sq_receipt_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_sq_receipt_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'actor_user_id', 'session_id'], ['workbench_sessions.project_id', 'workbench_sessions.user_id', 'workbench_sessions.id'], name='fk_sq_receipt_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('command_id', name='uq_sq_command'),
    sa.UniqueConstraint('organization_id', 'project_id', 'actor_user_id', 'session_id', 'id', name='uq_sq_receipt_scope')
    )
    op.create_table('supplier_quote_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=True),
    sa.Column('predecessor_id', sa.Uuid(), nullable=True),
    sa.Column('source_revision_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('seal_id', sa.Uuid(), nullable=False),
    sa.Column('pre_row_version', sa.Integer(), nullable=False),
    sa.Column('post_row_version', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('invocation_binding', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind IN ('registration', 'revision') AND revision_id IS NULL AND revision_number > 0) OR (kind IN ('line-registration', 'confirmation', 'withdrawal', 'rejection') AND revision_id IS NOT NULL AND revision_number IS NULL AND predecessor_id IS NULL)", name='chk_sq_kind'),
    sa.CheckConstraint('pre_row_version > 0 AND post_row_version = pre_row_version + 1', name='chk_sq_versions'),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_events.id'], name='fk_sq_audit', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'actor_user_id'], ['users.organization_id', 'users.id'], name='fk_sq_fact_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'actor_user_id', 'session_id', 'receipt_id'], ['supplier_quote_receipts.organization_id', 'supplier_quote_receipts.project_id', 'supplier_quote_receipts.actor_user_id', 'supplier_quote_receipts.session_id', 'supplier_quote_receipts.id'], name='fk_sq_receipt', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'predecessor_id'], ['supplier_quote_facts.organization_id', 'supplier_quote_facts.project_id', 'supplier_quote_facts.id'], name='fk_sq_predecessor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'quote_id', 'source_revision_id'], ['document_revisions.organization_id', 'document_revisions.project_id', 'document_revisions.document_id', 'document_revisions.id'], name='fk_sq_source_revision', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'revision_id'], ['supplier_quote_facts.organization_id', 'supplier_quote_facts.project_id', 'supplier_quote_facts.id'], name='fk_sq_revision', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'seal_id'], ['project_asset_review_seals.organization_id', 'project_asset_review_seals.project_id', 'project_asset_review_seals.id'], name='fk_sq_seal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id'], ['projects.organization_id', 'projects.id'], name='fk_sq_fact_project', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'source_revision_id'], ['storage_object_bindings.organization_id', 'storage_object_bindings.document_revision_id'], name='fk_sq_retained_source', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'supplier_id'], ['suppliers.organization_id', 'suppliers.id'], name='fk_sq_supplier', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'actor_user_id', 'session_id'], ['workbench_sessions.project_id', 'workbench_sessions.user_id', 'workbench_sessions.id'], name='fk_sq_fact_session', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', name='uq_sq_fact_audit'),
    sa.UniqueConstraint('organization_id', 'project_id', 'id', name='uq_sq_fact_scope'),
    sa.UniqueConstraint('organization_id', 'project_id', 'quote_id', 'post_row_version', name='uq_sq_fact_order'),
    sa.UniqueConstraint('organization_id', 'project_id', 'quote_id', 'revision_number', name='uq_sq_revision'),
    sa.UniqueConstraint('predecessor_id', name='uq_sq_successor'),
    sa.UniqueConstraint('receipt_id', name='uq_sq_fact_receipt')
    )
    op.create_table('supplier_quote_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('fact_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=26, scale=8), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=26, scale=8), nullable=False),
    sa.Column('unit', sa.String(length=2000), nullable=False),
    sa.Column('source_locator', sa.String(length=120), nullable=False),
    sa.CheckConstraint('quantity > 0 AND unit_price > 0', name='chk_sq_item_amounts'),
    sa.ForeignKeyConstraint(['organization_id', 'project_id', 'fact_id'], ['supplier_quote_facts.organization_id', 'supplier_quote_facts.project_id', 'supplier_quote_facts.id'], name='fk_sq_item_fact', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'line_id'], ['project_asset_lines.project_id', 'project_asset_lines.id'], name='fk_sq_item_line', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_id', 'line_id', name='uq_sq_item_line')
    )
    # ### end Alembic commands ###
    install_guards()


def install_guards():
    if op.get_context().dialect.name == "postgresql":
        op.execute("CREATE FUNCTION supplier_quotes_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ "
            "BEGIN RAISE EXCEPTION 'SUPPLIER_QUOTES facts are append-only'; END; $$")
        for table in TABLES:
            op.execute(f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION supplier_quotes_append_only()")
        op.execute("CREATE FUNCTION supplier_quotes_pinned_source() RETURNS trigger LANGUAGE plpgsql AS $$ "
            "DECLARE referenced boolean; source_id uuid; BEGIN "
            "source_id := CASE WHEN TG_TABLE_NAME = 'document_revisions' THEN OLD.id ELSE (to_jsonb(OLD)->>'document_revision_id')::uuid END; "
            "EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I.supplier_quote_facts WHERE organization_id = $1 AND source_revision_id = $2)', TG_TABLE_SCHEMA) "
            "INTO referenced USING OLD.organization_id, source_id; "
            "IF referenced THEN RAISE EXCEPTION 'Admitted supplier quote source is immutable'; END IF; "
            "IF TG_OP = 'DELETE' THEN RETURN OLD; END IF; RETURN NEW; END; $$")
        for table in ('document_revisions', 'storage_object_bindings'):
            op.execute(f"CREATE TRIGGER {table}_sq_pin BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION supplier_quotes_pinned_source()")


def downgrade():
    if op.get_context().dialect.name == "postgresql":
        for table in ('document_revisions', 'storage_object_bindings'):
            op.execute(f"DROP TRIGGER {table}_sq_pin ON {table}")
        op.execute("DROP FUNCTION supplier_quotes_pinned_source()")
    for table in reversed(TABLES):
        op.drop_table(table)
    if op.get_context().dialect.name == "postgresql":
        op.execute("DROP FUNCTION supplier_quotes_append_only()")
